const coins = [
  {
    symbol: "btc",
    price_change_percentage_1h_in_currency: 12.34,
  },
  {
    symbol: "eth",
    price_change_percentage_1h_in_currency: -14.87,
  },
  {
    symbol: "sol",
    price_change_percentage_1h_in_currency: 4.12,
  },
  {
    symbol: "dot",
    price_change_percentage_1h_in_currency: -3.45,
  },
  {
    symbol: "ada",
    price_change_percentage_1h_in_currency: 1.23,
  },
  {
    symbol: "xrp",
    price_change_percentage_1h_in_currency: -2.91,
  },
  {
    symbol: "link",
    price_change_percentage_1h_in_currency: 3.78,
  },
  {
    symbol: "matic",
    price_change_percentage_1h_in_currency: -4.56,
  },
  {
    symbol: "avax",
    price_change_percentage_1h_in_currency: 2.89,
  },
  {
    symbol: "doge",
    price_change_percentage_1h_in_currency: -1.45,
  },
  {
    symbol: "shib",
    price_change_percentage_1h_in_currency: 5.67,
  },
  {
    symbol: "uni",
    price_change_percentage_1h_in_currency: -3.21,
  },
  {
    symbol: "ltc",
    price_change_percentage_1h_in_currency: 1.98,
  },
  {
    symbol: "atom",
    price_change_percentage_1h_in_currency: -2.34,
  },
  {
    symbol: "near",
    price_change_percentage_1h_in_currency: 4.56,
  },
  {
    symbol: "algo",
    price_change_percentage_1h_in_currency: -1.78,
  },
  {
    symbol: "ftm",
    price_change_percentage_1h_in_currency: 6.89,
  },
  {
    symbol: "icp",
    price_change_percentage_1h_in_currency: -5.43,
  },
  {
    symbol: "vet",
    price_change_percentage_1h_in_currency: 2.11,
  },
  {
    symbol: "sand",
    price_change_percentage_1h_in_currency: -4.32,
  },
  {
    symbol: "mana",
    price_change_percentage_1h_in_currency: 3.45,
  },
  {
    symbol: "grt",
    price_change_percentage_1h_in_currency: -2.67,
  },
  {
    symbol: "one",
    price_change_percentage_1h_in_currency: 1.89,
  },
  {
    symbol: "enj",
    price_change_percentage_1h_in_currency: -3.78,
  },
  {
    symbol: "chz",
    price_change_percentage_1h_in_currency: 4.23,
  },
  {
    symbol: "bat",
    price_change_percentage_1h_in_currency: -1.56,
  },
  {
    symbol: "zil",
    price_change_percentage_1h_in_currency: 2.78,
  },
  {
    symbol: "mkr",
    price_change_percentage_1h_in_currency: -4.89,
  },
  {
    symbol: "snx",
    price_change_percentage_1h_in_currency: 3.12,
  },
  {
    symbol: "comp",
    price_change_percentage_1h_in_currency: -2.45,
  },
];
const marqueeTokens = [
  {
    rank: "#1",
    name: "TRUMP",
    change: "-8.73%",
    isPositive: false,
    logo: "/dummy-token.jpg",
    price: "$0.0234",
  },
  {
    rank: "#2",
    name: "VINE",
    change: "-24.25%",
    isPositive: false,
    logo: "/dummy-token.jpg",
    price: "$1.234",
  },
  {
    rank: "#3",
    name: "RUG",
    change: "+37.66%",
    isPositive: true,
    logo: "/dummy-token.jpg",
    price: "$0.567",
  },
  {
    rank: "#4",
    name: "SAGA",
    change: "+15.23%",
    isPositive: true,
    logo: "/dummy-token.jpg",
    price: "$2.345",
  },
  {
    rank: "#5",
    name: "PEPE",
    change: "-12.45%",
    isPositive: false,
    logo: "/dummy-token.jpg",
    price: "$0.789",
  },
  {
    rank: "#6",
    name: "DOGE",
    change: "+5.67%",
    isPositive: true,
    logo: "/dummy-token.jpg",
    price: "$0.145",
  },
];

const recentTrades = [
  {
    token: "TRUMP",
    tokenLogo: "/dummy-token.jpg",
    value: "$10.71K",
    trade: {
      sell: "-10.72K USDC",
      buy: "+2.59K TRUMP",
    },
    trader: "0x46f08032",
    time: "6m ago",
  },
  {
    token: "SAGA",
    tokenLogo: "/dummy-token.jpg",
    value: "$12.3K",
    trade: {
      sell: "-5.2K SAGA",
      buy: "+15.5K USDC",
    },
    trader: "0x62310ee2",
    time: "8m ago",
  },
  {
    token: "PEPE",
    tokenLogo: "/dummy-token.jpg",
    value: "$8.45K",
    trade: {
      sell: "-8.45K USDC",
      buy: "+1.2M PEPE",
    },
    trader: "0x89ab23cd",
    time: "12m ago",
  },
  {
    token: "WOJAK",
    tokenLogo: "/dummy-token.jpg",
    value: "$15.2K",
    trade: {
      sell: "-15.2K USDC",
      buy: "+45K WOJAK",
    },
    trader: "0x34de56fa",
    time: "15m ago",
  },
  {
    token: "DOGE",
    tokenLogo: "/dummy-token.jpg",
    value: "$25.6K",
    trade: {
      sell: "-25.6K USDC",
      buy: "+180K DOGE",
    },
    trader: "0x78bc45de",
    time: "18m ago",
  },
  {
    token: "BONK",
    tokenLogo: "/dummy-token.jpg",
    value: "$5.8K",
    trade: {
      sell: "-2.1M BONK",
      buy: "+5.8K USDC",
    },
    trader: "0x12ef34ab",
    time: "22m ago",
  },
  {
    token: "SHIB",
    tokenLogo: "/dummy-token.jpg",
    value: "$19.3K",
    trade: {
      sell: "-19.3K USDC",
      buy: "+2.8B SHIB",
    },
    trader: "0x56cd78ef",
    time: "25m ago",
  },
  {
    token: "MATIC",
    tokenLogo: "/dummy-token.jpg",
    value: "$32.1K",
    trade: {
      sell: "-45K MATIC",
      buy: "+32.1K USDC",
    },
    trader: "0x90ab12cd",
    time: "28m ago",
  },
  {
    token: "LINK",
    tokenLogo: "/dummy-token.jpg",
    value: "$28.7K",
    trade: {
      sell: "-28.7K USDC",
      buy: "+1.8K LINK",
    },
    trader: "0x45ef67ab",
    time: "32m ago",
  },
  {
    token: "SOL",
    tokenLogo: "/dummy-token.jpg",
    value: "$45.2K",
    trade: {
      sell: "-580 SOL",
      buy: "+45.2K USDC",
    },
    trader: "0x23cd45ef",
    time: "35m ago",
  },
  {
    token: "APT",
    tokenLogo: "/dummy-token.jpg",
    value: "$22.4K",
    trade: {
      sell: "-22.4K USDC",
      buy: "+890 APT",
    },
    trader: "0x67ab89cd",
    time: "38m ago",
  },
  {
    token: "ARB",
    tokenLogo: "/dummy-token.jpg",
    value: "$16.9K",
    trade: {
      sell: "-12K ARB",
      buy: "+16.9K USDC",
    },
    trader: "0x34ef56cd",
    time: "42m ago",
  },
];

const topTraders = [
  {
    address: "0x1234...5678",
    avatar: "/dummy-token.jpg",
    pnl7d: "+$146.11M",
    volume: "$238.63M",
  },
  {
    address: "0x8765...4321",
    avatar: "/dummy-token.jpg",
    pnl7d: "+$125.29M",
    volume: "$323.29M",
  },
  {
    address: "0xabcd...ef12",
    avatar: "/dummy-token.jpg",
    pnl7d: "+$98.45M",
    volume: "$412.67M",
  },
  {
    address: "0x9876...dcba",
    avatar: "/dummy-token.jpg",
    pnl7d: "-$45.32M",
    volume: "$178.91M",
  },
  {
    address: "0xdef4...5678",
    avatar: "/dummy-token.jpg",
    pnl7d: "+$67.83M",
    volume: "$245.16M",
  },
  {
    address: "0x4567...89ab",
    avatar: "/dummy-token.jpg",
    pnl7d: "+$88.92M",
    volume: "$356.74M",
  },
  {
    address: "0x3333...7777",
    avatar: "/dummy-token.jpg",
    pnl7d: "-$23.45M",
    volume: "$167.82M",
  },
  {
    address: "0xaaaa...bbbb",
    avatar: "/dummy-token.jpg",
    pnl7d: "+$54.67M",
    volume: "$198.34M",
  },
  {
    address: "0x1111...2222",
    avatar: "/dummy-token.jpg",
    pnl7d: "+$72.19M",
    volume: "$289.45M",
  },
  {
    address: "0xcccc...dddd",
    avatar: "/dummy-token.jpg",
    pnl7d: "-$34.78M",
    volume: "$145.92M",
  },
];

const tokens = [
  {
    logo: "/dummy-token.jpg",
    name: "G.A.M.E",
    symbol: "$GAME",
    address: "0x1CHC...F463a3",
    category: "Productivity",
    marketCap: "$79.18m",
    change24h: "+8.85%",
    tvl: "$13.48m",
    holders: "182,395",
    volume24h: "$1.26m",
  },
  {
    logo: "/dummy-token.jpg",
    name: "Luna",
    symbol: "$LUNA",
    address: "0x5cb...2d7ee4",
    category: "Entertainment",
    marketCap: "$34.57m",
    change24h: "-2.2%",
    tvl: "$6.89m",
    holders: "288,041",
    volume24h: "$301.85k",
  },
  {
    logo: "/dummy-token.jpg",
    name: "Pepe",
    symbol: "$PEPE",
    address: "0x8df...a91bc2",
    category: "Meme",
    marketCap: "$145.32m",
    change24h: "+15.7%",
    tvl: "$28.45m",
    holders: "542,891",
    volume24h: "$3.45m",
  },
  {
    logo: "/dummy-token.jpg",
    name: "DefiX",
    symbol: "$DFX",
    address: "0x3ae...c72dd1",
    category: "DeFi",
    marketCap: "$92.64m",
    change24h: "-5.4%",
    tvl: "$45.21m",
    holders: "124,567",
    volume24h: "$892.45k",
  },
  {
    logo: "/dummy-token.jpg",
    name: "MetaVerse",
    symbol: "$META",
    address: "0x9fe...b45ea2",
    category: "Virtual Reality",
    marketCap: "$218.93m",
    change24h: "+12.8%",
    tvl: "$67.34m",
    holders: "295,678",
    volume24h: "$5.67m",
  },
  {
    logo: "/dummy-token.jpg",
    name: "ArtBlock",
    symbol: "$ART",
    address: "0x2bc...e83ff4",
    category: "NFT",
    marketCap: "$56.78m",
    change24h: "-8.3%",
    tvl: "$12.45m",
    holders: "89,234",
    volume24h: "$456.78k",
  },
  {
    logo: "/dummy-token.jpg",
    name: "SportFi",
    symbol: "$SPORT",
    address: "0x7ac...d92ee5",
    category: "Sports",
    marketCap: "$127.45m",
    change24h: "+6.9%",
    tvl: "$34.56m",
    holders: "167,890",
    volume24h: "$2.34m",
  },
  {
    logo: "/dummy-token.jpg",
    name: "AIToken",
    symbol: "$AIT",
    address: "0x4ed...f67cc3",
    category: "AI",
    marketCap: "$165.89m",
    change24h: "+23.4%",
    tvl: "$52.67m",
    holders: "234,567",
    volume24h: "$4.89m",
  },
  {
    logo: "/dummy-token.jpg",
    name: "Carbon",
    symbol: "$CRBN",
    address: "0x6ff...a45db1",
    category: "Climate",
    marketCap: "$83.56m",
    change24h: "-3.7%",
    tvl: "$21.34m",
    holders: "145,678",
    volume24h: "$789.23k",
  },
];

export { coins, marqueeTokens, recentTrades, tokens, topTraders };
